import { defaultUrlTransform } from "react-markdown";
import { defaultSchema } from "rehype-sanitize";

// Class names added by remark-gfm for task lists
export const TASK_LIST_CLASS = "contains-task-list";
export const TASK_LIST_ITEM_CLASS = "task-list-item";

const TRUSTED_IFRAME_SRC_PATTERNS = [
  /^https:\/\/www\.youtube\.com\/embed\/[^?#]+(?:\?.*)?$/i,
  /^https:\/\/www\.youtube-nocookie\.com\/embed\/[^?#]+(?:\?.*)?$/i,
  /^https:\/\/player\.vimeo\.com\/video\/[^?#]+(?:\?.*)?$/i,
  /^https:\/\/open\.spotify\.com\/embed\/[^?#]+(?:\?.*)?$/i,
  /^https:\/\/w\.soundcloud\.com\/player\/?(?:\?.*)?$/i,
  /^https:\/\/www\.loom\.com\/embed\/[^?#]+(?:\?.*)?$/i,
  /^https:\/\/www\.google\.com\/maps\/embed(?:\/[^?#]*)?(?:\?.*)?$/i,
  /^https:\/\/(?:app\.)?diagrams\.net\/(?:[^?#]+)?(?:\?.*)?$/i,
  /^https:\/\/(?:www\.)?draw\.io\/(?:[^?#]+)?(?:\?.*)?$/i,
];

const KATEX_INLINE_CLASS_NAMES = ["language-math", "math-inline"] as const;
const KATEX_BLOCK_CLASS_NAMES = ["language-math", "math-display"] as const;
const SPAN_CLASS_NAMES = ["mention", "tag"] as const;
const INPUT_ATTRIBUTES = [...(defaultSchema.attributes?.input || []), ["checked", true]] as const;

/**
 * Link schemes the browser hands off to another app (dialer, messaging) instead of navigating.
 * They cannot run script, so they are as safe as the `mailto:` the default schema already allows.
 */
const HANDOFF_LINK_PROTOCOLS = ["tel", "sms"];

export const isTrustedIframeSrc = (src: string): boolean => TRUSTED_IFRAME_SRC_PATTERNS.some((pattern) => pattern.test(src));

/**
 * Sanitization schema for markdown HTML content.
 * Extends the default schema to allow:
 * - KaTeX marker classes used before trusted KaTeX rendering runs
 * - Mention/tag metadata generated by trusted remark plugins
 * - iframe embeds only from trusted video providers
 *
 * This prevents XSS attacks while preserving math rendering functionality.
 */
export const SANITIZE_SCHEMA = {
  ...defaultSchema,
  // Don't re-prefix `id`/`name` attributes. remark-rehype already namespaces footnote ids with
  // `user-content-` and emits matching `#user-content-…` hrefs; the default schema's clobbering
  // would prepend a *second* `user-content-` to the ids only (not the hrefs), breaking in-page
  // navigation. Leaving ids untouched keeps footnote (and heading) anchors pointing at real targets.
  clobber: [],
  attributes: {
    ...defaultSchema.attributes,
    img: [...(defaultSchema.attributes?.img || []), "height", "width"],
    input: INPUT_ATTRIBUTES,
    code: [...(defaultSchema.attributes?.code || []), ["className", ...KATEX_INLINE_CLASS_NAMES, ...KATEX_BLOCK_CLASS_NAMES]],
    span: [...(defaultSchema.attributes?.span || []), ["className", ...SPAN_CLASS_NAMES], ["aria*"], ["data*"]],
    iframe: [
      ["src", ...TRUSTED_IFRAME_SRC_PATTERNS],
      "width",
      "height",
      "frameborder",
      "allowfullscreen",
      "allow",
      "title",
      "referrerpolicy",
      "loading",
    ],
  },
  // `picture`/`source` carry `srcSet`, which the https-only `src` rule below does not cover;
  // drop them so every remote image goes through the `img` `src` rule.
  tagNames: [...(defaultSchema.tagNames || []).filter((tag) => tag !== "picture" && tag !== "source"), "iframe"],
  protocols: {
    ...defaultSchema.protocols,
    href: [...(defaultSchema.protocols?.href || []), ...HANDOFF_LINK_PROTOCOLS],
    src: ["https"],
  },
};

/**
 * react-markdown applies its own `href` allowlist (`defaultUrlTransform`) before the sanitizer
 * runs, and it does not know about the handoff schemes above. Let those through unchanged and
 * defer everything else to the default, so `javascript:` and friends are still dropped.
 */
export const memoUrlTransform = (url: string): string => {
  // Exact-case match, mirroring how the sanitizer compares schemes.
  const colon = url.indexOf(":");
  if (colon > 0 && HANDOFF_LINK_PROTOCOLS.includes(url.slice(0, colon))) {
    return url;
  }
  return defaultUrlTransform(url);
};
