import type { Element, Root } from "hast";
import { visit } from "unist-util-visit";
import { createUniqueSlugGenerator, slugify } from "@/utils/markdown-manipulation";

/** Anchor used for headings with no slugifiable characters (emoji- or punctuation-only titles). */
const FALLBACK_HEADING_SLUG = "heading";

export const isHeadingElement = (node: Element): boolean => /^h[1-6]$/.test(node.tagName);

/** Rendered text of a heading: element children contribute their text, everything else nothing. */
export function getHeadingText(node: Element): string {
  let text = "";
  for (const child of node.children) {
    if (child.type === "text") {
      text += child.value;
    } else if (child.type === "element") {
      text += getHeadingText(child);
    }
  }
  return text;
}

/**
 * Rehype plugin that adds unique slugified `id` attributes to heading elements. This is the
 * single place a heading anchor is decided: the memo outline reads these ids back off the tree
 * rather than deriving its own, so an outline link always has somewhere to land.
 *
 * Every heading consumes a slug — including h5/h6 and titles that slugify to nothing — because
 * the duplicate suffixes depend on how many headings came before.
 */
export const rehypeHeadingId = () => {
  return (tree: Root) => {
    // Reserve ids supplied by the source or generated by remark-rehype before assigning any new
    // ones. Otherwise an earlier markdown heading can take `footnote-label`, forcing the linked
    // screen-reader footnote label to be renamed without updating its aria-describedby references.
    const existingIds = new Set<string>();
    visit(tree, "element", (node: Element) => {
      if (!isHeadingElement(node)) return;
      const existingId = typeof node.properties?.id === "string" ? node.properties.id : "";
      if (existingId) existingIds.add(existingId);
    });

    const makeUniqueSlug = createUniqueSlugGenerator(existingIds);
    const claimedExistingIds = new Set<string>();

    visit(tree, "element", (node: Element) => {
      if (!isHeadingElement(node)) return;

      node.properties = node.properties || {};
      const existingId = typeof node.properties.id === "string" ? node.properties.id : "";
      // An id that is already there is linked to from somewhere — remark-rehype points each
      // footnote reference's aria-describedby at its generated label. Keep it, and reserve it so a
      // later heading cannot be given the same slug.
      if (existingId && !claimedExistingIds.has(existingId)) {
        claimedExistingIds.add(existingId);
        node.properties.id = existingId;
      } else {
        node.properties.id = makeUniqueSlug(existingId || slugify(getHeadingText(node)) || FALLBACK_HEADING_SLUG);
      }
    });
  };
};
