# fly.toml app configuration file generated for memos-bv6xyg on 2026-06-05T07:13:51Z

app = 'memos-bv6xyg'
primary_region = 'ams'

[build]
  dockerfile = "Dockerfile"

[env]
  MEMOS_PORT = '5230'

[http_service]
  internal_port = 5230
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256