# fly.toml app configuration file generated for memos-bv6xyg on 2026-06-05T08:02:40Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'memos-bv6xyg'
primary_region = 'ams'

[build]
  dockerfile = 'scripts/Dockerfile'

  [build.args]
    GO_VERSION = '1.26.2'

[env]
  MEMOS_PORT = '5230'
  MEMOS_DRIVER = 'postgres'

[http_service]
  internal_port = 5230
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
