// Common Space identities. Any supported Unicode emoji can also be pasted into the picker.
export const SPACE_EMOJI = [
  ["🌱", "Seedling plant garden growth"],
  ["📚", "Books reading library"],
  ["💼", "Briefcase work business"],
  ["🏠", "House home family"],
  ["💡", "Light bulb ideas"],
  ["🚀", "Rocket launch project"],
  ["🎨", "Artist palette design art"],
  ["✍️", "Writing hand journal"],
  ["📝", "Memo notes writing"],
  ["🧠", "Brain learning knowledge"],
  ["🎯", "Target goals"],
  ["⭐", "Star favorites"],
  ["❤️", "Heart love"],
  ["🔥", "Fire energy"],
  ["⚡", "Lightning bolt power"],
  ["☀️", "Sun sunshine"],
  ["🌙", "Moon night"],
  ["🌈", "Rainbow colors"],
  ["🌊", "Wave ocean water"],
  ["🍀", "Four leaf clover luck"],
  ["🌸", "Cherry blossom flower"],
  ["🌻", "Sunflower"],
  ["🌳", "Tree forest nature"],
  ["🍄", "Mushroom"],
  ["🐈", "Cat pet"],
  ["🐕", "Dog pet"],
  ["🦊", "Fox"],
  ["🐼", "Panda"],
  ["🦋", "Butterfly"],
  ["🐝", "Bee honey"],
  ["🐙", "Octopus"],
  ["🐳", "Whale"],
  ["☕", "Coffee drink cafe"],
  ["🍵", "Tea cup"],
  ["🍎", "Apple fruit food"],
  ["🍋", "Lemon fruit"],
  ["🥑", "Avocado"],
  ["🍕", "Pizza cooking food"],
  ["🍰", "Cake dessert baking"],
  ["🍷", "Wine glass"],
  ["🎵", "Music note"],
  ["🎸", "Guitar music"],
  ["🎬", "Clapper board movies film"],
  ["📷", "Camera photography"],
  ["🎮", "Game controller gaming"],
  ["🎲", "Dice games"],
  ["⚽", "Soccer football sport"],
  ["🏀", "Basketball sport"],
  ["🚲", "Bicycle cycling"],
  ["🏆", "Trophy achievement"],
  ["✈️", "Airplane travel"],
  ["🏕️", "Camping tent outdoors"],
  ["🏔️", "Mountain hiking"],
  ["🏖️", "Beach holiday"],
  ["🌍", "Earth world globe"],
  ["🧭", "Compass exploration"],
  ["🔬", "Microscope research science"],
  ["🧪", "Test tube experiment"],
  ["💻", "Laptop code technology"],
  ["🛠️", "Tools building"],
  ["🧩", "Puzzle piece"],
  ["💎", "Gem diamond"],
  ["🎓", "Graduation education study"],
  ["🎉", "Party celebration"],
] as const;
