import {
  AstroidIcon,
  BookOpenIcon,
  BriefcaseIcon,
  CameraIcon,
  ChartNoAxesCombinedIcon,
  CheckCheckIcon,
  CodeIcon,
  CoffeeIcon,
  CompassIcon,
  EarthIcon,
  FeatherIcon,
  FlaskConicalIcon,
  Flower2Icon,
  FolderIcon,
  GemIcon,
  GraduationCapIcon,
  HeartIcon,
  HouseIcon,
  LeafIcon,
  LightbulbIcon,
  MapPinIcon,
  MountainIcon,
  MusicIcon,
  NotebookPenIcon,
  PaletteIcon,
  PencilIcon,
  PlaneIcon,
  RocketIcon,
  SproutIcon,
  StarIcon,
  SunIcon,
  TargetIcon,
  TentIcon,
  TrophyIcon,
  UsersIcon,
  UtensilsIcon,
  WrenchIcon,
  ZapIcon,
} from "lucide-react";
import type { Space_Icon } from "@/types/proto/api/v1/space_service_pb";

// Keep the catalog explicit so adding a picker does not bundle the entire icon library.
export const SPACE_SYMBOLS = {
  astroid: AstroidIcon,
  "book-open": BookOpenIcon,
  briefcase: BriefcaseIcon,
  camera: CameraIcon,
  "chart-no-axes-combined": ChartNoAxesCombinedIcon,
  "check-check": CheckCheckIcon,
  code: CodeIcon,
  coffee: CoffeeIcon,
  compass: CompassIcon,
  earth: EarthIcon,
  feather: FeatherIcon,
  "flask-conical": FlaskConicalIcon,
  "flower-2": Flower2Icon,
  folder: FolderIcon,
  gem: GemIcon,
  "graduation-cap": GraduationCapIcon,
  heart: HeartIcon,
  house: HouseIcon,
  leaf: LeafIcon,
  lightbulb: LightbulbIcon,
  "map-pin": MapPinIcon,
  mountain: MountainIcon,
  music: MusicIcon,
  "notebook-pen": NotebookPenIcon,
  palette: PaletteIcon,
  pencil: PencilIcon,
  plane: PlaneIcon,
  rocket: RocketIcon,
  sprout: SproutIcon,
  star: StarIcon,
  sun: SunIcon,
  target: TargetIcon,
  tent: TentIcon,
  trophy: TrophyIcon,
  users: UsersIcon,
  utensils: UtensilsIcon,
  wrench: WrenchIcon,
  zap: ZapIcon,
};

export const getSpaceSymbol = (name: string) =>
  Object.hasOwn(SPACE_SYMBOLS, name) ? SPACE_SYMBOLS[name as keyof typeof SPACE_SYMBOLS] : AstroidIcon;

export const spaceIconsEqual = (a?: Space_Icon, b?: Space_Icon) => a?.value.case === b?.value.case && a?.value.value === b?.value.value;
