// @generated by protoc-gen-es v1.3.0
// @generated from file api/v2/memo_service.proto (package memos.api.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { RowStatus } from "./common_pb.js";

/**
 * @generated from enum memos.api.v2.Visibility
 */
export declare enum Visibility {
  /**
   * @generated from enum value: VISIBILITY_UNSPECIFIED = 0;
   */
  VISIBILITY_UNSPECIFIED = 0,

  /**
   * @generated from enum value: PRIVATE = 1;
   */
  PRIVATE = 1,

  /**
   * @generated from enum value: PROTECTED = 2;
   */
  PROTECTED = 2,

  /**
   * @generated from enum value: PUBLIC = 3;
   */
  PUBLIC = 3,
}

/**
 * @generated from message memos.api.v2.Memo
 */
export declare class Memo extends Message<Memo> {
  /**
   * @generated from field: int32 id = 1;
   */
  id: number;

  /**
   * @generated from field: memos.api.v2.RowStatus row_status = 2;
   */
  rowStatus: RowStatus;

  /**
   * @generated from field: int32 creator_id = 3;
   */
  creatorId: number;

  /**
   * @generated from field: int64 created_ts = 4;
   */
  createdTs: bigint;

  /**
   * @generated from field: int64 updated_ts = 5;
   */
  updatedTs: bigint;

  /**
   * @generated from field: string content = 6;
   */
  content: string;

  /**
   * @generated from field: memos.api.v2.Visibility visibility = 7;
   */
  visibility: Visibility;

  /**
   * @generated from field: bool pinned = 8;
   */
  pinned: boolean;

  constructor(data?: PartialMessage<Memo>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "memos.api.v2.Memo";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Memo;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Memo;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Memo;

  static equals(a: Memo | PlainMessage<Memo> | undefined, b: Memo | PlainMessage<Memo> | undefined): boolean;
}

/**
 * @generated from message memos.api.v2.ListMemosRequest
 */
export declare class ListMemosRequest extends Message<ListMemosRequest> {
  /**
   * @generated from field: int32 page = 1;
   */
  page: number;

  /**
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;

  /**
   * Filter is used to filter memos returned in the list.
   *
   * @generated from field: string filter = 3;
   */
  filter: string;

  constructor(data?: PartialMessage<ListMemosRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "memos.api.v2.ListMemosRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListMemosRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListMemosRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListMemosRequest;

  static equals(a: ListMemosRequest | PlainMessage<ListMemosRequest> | undefined, b: ListMemosRequest | PlainMessage<ListMemosRequest> | undefined): boolean;
}

/**
 * @generated from message memos.api.v2.ListMemosResponse
 */
export declare class ListMemosResponse extends Message<ListMemosResponse> {
  /**
   * @generated from field: repeated memos.api.v2.Memo memos = 1;
   */
  memos: Memo[];

  constructor(data?: PartialMessage<ListMemosResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "memos.api.v2.ListMemosResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListMemosResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListMemosResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListMemosResponse;

  static equals(a: ListMemosResponse | PlainMessage<ListMemosResponse> | undefined, b: ListMemosResponse | PlainMessage<ListMemosResponse> | undefined): boolean;
}

/**
 * @generated from message memos.api.v2.GetMemoRequest
 */
export declare class GetMemoRequest extends Message<GetMemoRequest> {
  /**
   * @generated from field: int32 id = 1;
   */
  id: number;

  constructor(data?: PartialMessage<GetMemoRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "memos.api.v2.GetMemoRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetMemoRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetMemoRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetMemoRequest;

  static equals(a: GetMemoRequest | PlainMessage<GetMemoRequest> | undefined, b: GetMemoRequest | PlainMessage<GetMemoRequest> | undefined): boolean;
}

/**
 * @generated from message memos.api.v2.GetMemoResponse
 */
export declare class GetMemoResponse extends Message<GetMemoResponse> {
  /**
   * @generated from field: memos.api.v2.Memo memo = 1;
   */
  memo?: Memo;

  constructor(data?: PartialMessage<GetMemoResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "memos.api.v2.GetMemoResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetMemoResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetMemoResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetMemoResponse;

  static equals(a: GetMemoResponse | PlainMessage<GetMemoResponse> | undefined, b: GetMemoResponse | PlainMessage<GetMemoResponse> | undefined): boolean;
}

