// @generated by protoc-gen-es v1.3.0
// @generated from file api/v2/resource_service.proto (package memos.api.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message memos.api.v2.Resource
 */
export const Resource = proto3.makeMessageType(
  "memos.api.v2.Resource",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "created_ts", kind: "message", T: Timestamp },
    { no: 3, name: "filename", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "external_link", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "size", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 7, name: "related_memo_id", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
  ],
);

/**
 * @generated from message memos.api.v2.ListResourcesRequest
 */
export const ListResourcesRequest = proto3.makeMessageType(
  "memos.api.v2.ListResourcesRequest",
  [],
);

/**
 * @generated from message memos.api.v2.ListResourcesResponse
 */
export const ListResourcesResponse = proto3.makeMessageType(
  "memos.api.v2.ListResourcesResponse",
  () => [
    { no: 1, name: "resources", kind: "message", T: Resource, repeated: true },
  ],
);

