// @generated by protoc-gen-es v1.3.0
// @generated from file api/v2/system_service.proto (package memos.api.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message memos.api.v2.SystemInfo
 */
export declare class SystemInfo extends Message<SystemInfo> {
  /**
   * @generated from field: string version = 1;
   */
  version: string;

  /**
   * @generated from field: string mode = 2;
   */
  mode: string;

  /**
   * @generated from field: bool allow_registration = 3;
   */
  allowRegistration: boolean;

  /**
   * @generated from field: bool disable_password_login = 4;
   */
  disablePasswordLogin: boolean;

  /**
   * @generated from field: string additional_script = 5;
   */
  additionalScript: string;

  /**
   * @generated from field: string additional_style = 6;
   */
  additionalStyle: string;

  /**
   * @generated from field: int64 db_size = 7;
   */
  dbSize: bigint;

  constructor(data?: PartialMessage<SystemInfo>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "memos.api.v2.SystemInfo";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SystemInfo;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SystemInfo;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SystemInfo;

  static equals(a: SystemInfo | PlainMessage<SystemInfo> | undefined, b: SystemInfo | PlainMessage<SystemInfo> | undefined): boolean;
}

/**
 * @generated from message memos.api.v2.GetSystemInfoRequest
 */
export declare class GetSystemInfoRequest extends Message<GetSystemInfoRequest> {
  constructor(data?: PartialMessage<GetSystemInfoRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "memos.api.v2.GetSystemInfoRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSystemInfoRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSystemInfoRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSystemInfoRequest;

  static equals(a: GetSystemInfoRequest | PlainMessage<GetSystemInfoRequest> | undefined, b: GetSystemInfoRequest | PlainMessage<GetSystemInfoRequest> | undefined): boolean;
}

/**
 * @generated from message memos.api.v2.GetSystemInfoResponse
 */
export declare class GetSystemInfoResponse extends Message<GetSystemInfoResponse> {
  /**
   * @generated from field: memos.api.v2.SystemInfo system_info = 1;
   */
  systemInfo?: SystemInfo;

  constructor(data?: PartialMessage<GetSystemInfoResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "memos.api.v2.GetSystemInfoResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSystemInfoResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSystemInfoResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSystemInfoResponse;

  static equals(a: GetSystemInfoResponse | PlainMessage<GetSystemInfoResponse> | undefined, b: GetSystemInfoResponse | PlainMessage<GetSystemInfoResponse> | undefined): boolean;
}

