package v1

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"regexp"
	"strings"
)

// pollUIDPattern restricts poll UIDs to the shape actually generated by the
// frontend (uuidv4, see web/src/components/MemoEditor/Toolbar/CreatePollDialog.tsx).
// The UID is embedded in free-form memo content - user-controlled text - and
// flows unmodified into a URL path segment and this package's SQL layer, so
// constraining its shape server-side (mirroring the same check added to
// web/src/components/MemoContent/poll/types.ts) rules out oversized, or
// otherwise malformed poll blocks before they reach either.
var pollUIDPattern = regexp.MustCompile(`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`)

// pollDefinition is a poll's live definition as currently written in a
// memo's ``` poll fenced Markdown block - not a stored resource. It mirrors
// web/src/components/MemoContent/poll/types.ts's PollDefinition/parsePollDefinition
// exactly, so the server derives the same canonical shape the frontend
// renders, and hashes it the same way regardless of incidental JSON
// formatting (key order, whitespace).
type pollDefinition struct {
	ID       string
	Question string
	Type     string
	Options  []string
}

type rawPollDefinition struct {
	ID       string   `json:"id"`
	Question string   `json:"question"`
	Type     string   `json:"type"`
	Options  []string `json:"options"`
}

// findPollDefinitionInContent scans memo content for a ```poll fenced code
// block whose embedded JSON "id" equals pollUID, returning its parsed and
// normalized definition. Only a syntactically valid, present block counts:
// a stale or copy/paste-mismatched UID with no matching block in this memo's
// current content must not be treated as belonging to it.
func findPollDefinitionInContent(content, pollUID string) *pollDefinition {
	if !pollUIDPattern.MatchString(pollUID) {
		return nil
	}
	for _, body := range extractFencedCodeBlocks(content, pollLanguageTag) {
		var raw rawPollDefinition
		if err := json.Unmarshal([]byte(body), &raw); err != nil {
			continue
		}
		if raw.ID != pollUID {
			continue
		}
		def := normalizePollDefinition(&raw)
		if def == nil {
			continue
		}
		return def
	}
	return nil
}

const pollLanguageTag = "poll"

func normalizePollDefinition(raw *rawPollDefinition) *pollDefinition {
	if !pollUIDPattern.MatchString(raw.ID) {
		return nil
	}
	if strings.TrimSpace(raw.Question) == "" {
		return nil
	}
	options := make([]string, 0, len(raw.Options))
	for _, option := range raw.Options {
		option = strings.TrimSpace(option)
		if option != "" {
			options = append(options, option)
		}
	}
	if len(options) < 2 {
		return nil
	}
	pollType := "single"
	if raw.Type == "multiple" {
		pollType = "multiple"
	}
	return &pollDefinition{ID: raw.ID, Question: raw.Question, Type: pollType, Options: options}
}

// pollDefinitionHash hashes the parts of a poll definition that voting
// depends on - option identity, order, and single/multiple-choice mode -
// but deliberately not the question text, so fixing a typo in the question
// doesn't invalidate every vote already cast. Any change to the option set
// (add, remove, reorder, relabel) or the choice mode changes this hash,
// which EnsurePollBinding uses to detect drift and reset stale votes.
func pollDefinitionHash(def *pollDefinition) string {
	payload, _ := json.Marshal(struct {
		Type    string   `json:"type"`
		Options []string `json:"options"`
	}{
		Type:    def.Type,
		Options: def.Options,
	})
	hash := sha256.Sum256(payload)
	return hex.EncodeToString(hash[:])
}

// extractFencedCodeBlocks returns the body of every fenced code block in
// content whose info-string language tag equals lang, following CommonMark
// fenced-code-block rules closely enough for this purpose: a fence is 3+
// backticks; the block's content runs until a line that is only backticks,
// at least as many as the opening fence, or end of input.
func extractFencedCodeBlocks(content, lang string) []string {
	lines := strings.Split(content, "\n")
	var blocks []string
	i := 0
	for i < len(lines) {
		fenceLen, fenceLang, isOpen := parseFenceOpenLine(lines[i])
		if !isOpen {
			i++
			continue
		}
		bodyStart := i + 1
		j := bodyStart
		for j < len(lines) && !isFenceCloseLine(lines[j], fenceLen) {
			j++
		}
		if fenceLang == lang {
			blocks = append(blocks, strings.Join(lines[bodyStart:j], "\n"))
		}
		i = j + 1
	}
	return blocks
}

func parseFenceOpenLine(line string) (fenceLen int, lang string, ok bool) {
	trimmed := strings.TrimLeft(line, " \t")
	n := 0
	for n < len(trimmed) && trimmed[n] == '`' {
		n++
	}
	if n < 3 {
		return 0, "", false
	}
	return n, strings.TrimSpace(trimmed[n:]), true
}

func isFenceCloseLine(line string, minLen int) bool {
	trimmed := strings.TrimSpace(line)
	if trimmed == "" {
		return false
	}
	for _, r := range trimmed {
		if r != '`' {
			return false
		}
	}
	return len(trimmed) >= minLen
}
