package d1

import (
	"context"
	"strings"

	"github.com/pkg/errors"

	"github.com/usememos/memos/store"
)

const userIdentityColumns = "id, user_id, provider, extern_uid, created_ts, updated_ts"

// CreateUserIdentity links an external identity to a user.
func (d *DB) CreateUserIdentity(ctx context.Context, create *store.UserIdentity) (*store.UserIdentity, error) {
	query := "INSERT INTO user_identity (user_id, provider, extern_uid) VALUES (?, ?, ?) RETURNING id, created_ts, updated_ts"
	if err := d.db.QueryRowContext(ctx, query, create.UserID, create.Provider, create.ExternUID).Scan(&create.ID, &create.CreatedTs, &create.UpdatedTs); err != nil {
		return nil, errors.Wrap(err, "failed to create user identity")
	}
	return create, nil
}

// CreateUserWithIdentity inserts both rows in one batch. The identity cannot
// use the id generated by the user insert, because a batch never reads its
// own writes, so it resolves the user through the unique username and both
// rows are read back after the commit.
func (d *DB) CreateUserWithIdentity(ctx context.Context, createUser *store.User, createIdentity *store.UserIdentity) (*store.User, error) {
	b := newBatch()
	b.add("INSERT INTO user (username, role, email, nickname, password_hash, avatar_url) VALUES (?, ?, ?, ?, ?, ?)",
		createUser.Username, createUser.Role, nullableEmail(createUser.Email), createUser.Nickname, createUser.PasswordHash, createUser.AvatarURL)
	b.add("INSERT INTO user_identity (user_id, provider, extern_uid) SELECT id, ?, ? FROM user WHERE username = ?",
		createIdentity.Provider, createIdentity.ExternUID, createUser.Username)
	if _, err := b.commit(ctx, d); err != nil {
		return nil, errors.Wrap(err, "failed to create user with identity")
	}
	if err := d.db.QueryRowContext(ctx, "SELECT id, description, created_ts, updated_ts, row_status FROM user WHERE username = ?", createUser.Username).Scan(
		&createUser.ID, &createUser.Description, &createUser.CreatedTs, &createUser.UpdatedTs, &createUser.RowStatus,
	); err != nil {
		return nil, errors.Wrap(err, "failed to read created user")
	}
	if err := d.db.QueryRowContext(ctx, "SELECT id, user_id, created_ts, updated_ts FROM user_identity WHERE provider = ? AND extern_uid = ?", createIdentity.Provider, createIdentity.ExternUID).Scan(
		&createIdentity.ID, &createIdentity.UserID, &createIdentity.CreatedTs, &createIdentity.UpdatedTs,
	); err != nil {
		return nil, errors.Wrap(err, "failed to read created user identity")
	}
	return createUser, nil
}

// ListUserIdentities returns the identities matching find.
func (d *DB) ListUserIdentities(ctx context.Context, find *store.FindUserIdentity) ([]*store.UserIdentity, error) {
	where, args := []string{"1 = 1"}, []any{}
	if find.ID != nil {
		where, args = append(where, "id = ?"), append(args, *find.ID)
	}
	if find.UserID != nil {
		where, args = append(where, "user_id = ?"), append(args, *find.UserID)
	}
	if find.Provider != nil {
		where, args = append(where, "provider = ?"), append(args, *find.Provider)
	}
	if find.ExternUID != nil {
		where, args = append(where, "extern_uid = ?"), append(args, *find.ExternUID)
	}
	rows, err := d.db.QueryContext(ctx, "SELECT "+userIdentityColumns+" FROM user_identity WHERE "+strings.Join(where, " AND ")+" ORDER BY id ASC", args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	list := []*store.UserIdentity{}
	for rows.Next() {
		identity := &store.UserIdentity{}
		if err := rows.Scan(&identity.ID, &identity.UserID, &identity.Provider, &identity.ExternUID, &identity.CreatedTs, &identity.UpdatedTs); err != nil {
			return nil, err
		}
		list = append(list, identity)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return list, nil
}

// DeleteUserIdentities removes the identities matching delete.
func (d *DB) DeleteUserIdentities(ctx context.Context, delete *store.DeleteUserIdentity) error {
	where, args := []string{"1 = 1"}, []any{}
	if delete.ID != nil {
		where, args = append(where, "id = ?"), append(args, *delete.ID)
	}
	if delete.UserID != nil {
		where, args = append(where, "user_id = ?"), append(args, *delete.UserID)
	}
	if delete.Provider != nil {
		where, args = append(where, "provider = ?"), append(args, *delete.Provider)
	}
	_, err := d.execOne(ctx, "DELETE FROM user_identity WHERE "+strings.Join(where, " AND "), args...)
	return err
}
