// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/usememos/memos/ent/memo"
	"github.com/usememos/memos/ent/memorelation"
	"github.com/usememos/memos/ent/predicate"
)

// MemoQuery is the builder for querying Memo entities.
type MemoQuery struct {
	config
	ctx              *QueryContext
	order            []memo.OrderOption
	inters           []Interceptor
	predicates       []predicate.Memo
	withRelatedMemo  *MemoQuery
	withMemoRelation *MemoRelationQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MemoQuery builder.
func (mq *MemoQuery) Where(ps ...predicate.Memo) *MemoQuery {
	mq.predicates = append(mq.predicates, ps...)
	return mq
}

// Limit the number of records to be returned by this query.
func (mq *MemoQuery) Limit(limit int) *MemoQuery {
	mq.ctx.Limit = &limit
	return mq
}

// Offset to start from.
func (mq *MemoQuery) Offset(offset int) *MemoQuery {
	mq.ctx.Offset = &offset
	return mq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mq *MemoQuery) Unique(unique bool) *MemoQuery {
	mq.ctx.Unique = &unique
	return mq
}

// Order specifies how the records should be ordered.
func (mq *MemoQuery) Order(o ...memo.OrderOption) *MemoQuery {
	mq.order = append(mq.order, o...)
	return mq
}

// QueryRelatedMemo chains the current query on the "related_memo" edge.
func (mq *MemoQuery) QueryRelatedMemo() *MemoQuery {
	query := (&MemoClient{config: mq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(memo.Table, memo.FieldID, selector),
			sqlgraph.To(memo.Table, memo.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, memo.RelatedMemoTable, memo.RelatedMemoPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(mq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMemoRelation chains the current query on the "memo_relation" edge.
func (mq *MemoQuery) QueryMemoRelation() *MemoRelationQuery {
	query := (&MemoRelationClient{config: mq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(memo.Table, memo.FieldID, selector),
			sqlgraph.To(memorelation.Table, memorelation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, memo.MemoRelationTable, memo.MemoRelationColumn),
		)
		fromU = sqlgraph.SetNeighbors(mq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Memo entity from the query.
// Returns a *NotFoundError when no Memo was found.
func (mq *MemoQuery) First(ctx context.Context) (*Memo, error) {
	nodes, err := mq.Limit(1).All(setContextOp(ctx, mq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{memo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mq *MemoQuery) FirstX(ctx context.Context) *Memo {
	node, err := mq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Memo ID from the query.
// Returns a *NotFoundError when no Memo ID was found.
func (mq *MemoQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mq.Limit(1).IDs(setContextOp(ctx, mq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{memo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mq *MemoQuery) FirstIDX(ctx context.Context) int {
	id, err := mq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Memo entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Memo entity is found.
// Returns a *NotFoundError when no Memo entities are found.
func (mq *MemoQuery) Only(ctx context.Context) (*Memo, error) {
	nodes, err := mq.Limit(2).All(setContextOp(ctx, mq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{memo.Label}
	default:
		return nil, &NotSingularError{memo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mq *MemoQuery) OnlyX(ctx context.Context) *Memo {
	node, err := mq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Memo ID in the query.
// Returns a *NotSingularError when more than one Memo ID is found.
// Returns a *NotFoundError when no entities are found.
func (mq *MemoQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mq.Limit(2).IDs(setContextOp(ctx, mq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{memo.Label}
	default:
		err = &NotSingularError{memo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mq *MemoQuery) OnlyIDX(ctx context.Context) int {
	id, err := mq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Memos.
func (mq *MemoQuery) All(ctx context.Context) ([]*Memo, error) {
	ctx = setContextOp(ctx, mq.ctx, "All")
	if err := mq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Memo, *MemoQuery]()
	return withInterceptors[[]*Memo](ctx, mq, qr, mq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mq *MemoQuery) AllX(ctx context.Context) []*Memo {
	nodes, err := mq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Memo IDs.
func (mq *MemoQuery) IDs(ctx context.Context) (ids []int, err error) {
	if mq.ctx.Unique == nil && mq.path != nil {
		mq.Unique(true)
	}
	ctx = setContextOp(ctx, mq.ctx, "IDs")
	if err = mq.Select(memo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mq *MemoQuery) IDsX(ctx context.Context) []int {
	ids, err := mq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mq *MemoQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mq.ctx, "Count")
	if err := mq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mq, querierCount[*MemoQuery](), mq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mq *MemoQuery) CountX(ctx context.Context) int {
	count, err := mq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mq *MemoQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mq.ctx, "Exist")
	switch _, err := mq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mq *MemoQuery) ExistX(ctx context.Context) bool {
	exist, err := mq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MemoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mq *MemoQuery) Clone() *MemoQuery {
	if mq == nil {
		return nil
	}
	return &MemoQuery{
		config:           mq.config,
		ctx:              mq.ctx.Clone(),
		order:            append([]memo.OrderOption{}, mq.order...),
		inters:           append([]Interceptor{}, mq.inters...),
		predicates:       append([]predicate.Memo{}, mq.predicates...),
		withRelatedMemo:  mq.withRelatedMemo.Clone(),
		withMemoRelation: mq.withMemoRelation.Clone(),
		// clone intermediate query.
		sql:  mq.sql.Clone(),
		path: mq.path,
	}
}

// WithRelatedMemo tells the query-builder to eager-load the nodes that are connected to
// the "related_memo" edge. The optional arguments are used to configure the query builder of the edge.
func (mq *MemoQuery) WithRelatedMemo(opts ...func(*MemoQuery)) *MemoQuery {
	query := (&MemoClient{config: mq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mq.withRelatedMemo = query
	return mq
}

// WithMemoRelation tells the query-builder to eager-load the nodes that are connected to
// the "memo_relation" edge. The optional arguments are used to configure the query builder of the edge.
func (mq *MemoQuery) WithMemoRelation(opts ...func(*MemoRelationQuery)) *MemoQuery {
	query := (&MemoRelationClient{config: mq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mq.withMemoRelation = query
	return mq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ResourceName string `json:"resource_name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Memo.Query().
//		GroupBy(memo.FieldResourceName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mq *MemoQuery) GroupBy(field string, fields ...string) *MemoGroupBy {
	mq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MemoGroupBy{build: mq}
	grbuild.flds = &mq.ctx.Fields
	grbuild.label = memo.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ResourceName string `json:"resource_name,omitempty"`
//	}
//
//	client.Memo.Query().
//		Select(memo.FieldResourceName).
//		Scan(ctx, &v)
func (mq *MemoQuery) Select(fields ...string) *MemoSelect {
	mq.ctx.Fields = append(mq.ctx.Fields, fields...)
	sbuild := &MemoSelect{MemoQuery: mq}
	sbuild.label = memo.Label
	sbuild.flds, sbuild.scan = &mq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MemoSelect configured with the given aggregations.
func (mq *MemoQuery) Aggregate(fns ...AggregateFunc) *MemoSelect {
	return mq.Select().Aggregate(fns...)
}

func (mq *MemoQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mq); err != nil {
				return err
			}
		}
	}
	for _, f := range mq.ctx.Fields {
		if !memo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mq.path != nil {
		prev, err := mq.path(ctx)
		if err != nil {
			return err
		}
		mq.sql = prev
	}
	return nil
}

func (mq *MemoQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Memo, error) {
	var (
		nodes       = []*Memo{}
		_spec       = mq.querySpec()
		loadedTypes = [2]bool{
			mq.withRelatedMemo != nil,
			mq.withMemoRelation != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Memo).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Memo{config: mq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := mq.withRelatedMemo; query != nil {
		if err := mq.loadRelatedMemo(ctx, query, nodes,
			func(n *Memo) { n.Edges.RelatedMemo = []*Memo{} },
			func(n *Memo, e *Memo) { n.Edges.RelatedMemo = append(n.Edges.RelatedMemo, e) }); err != nil {
			return nil, err
		}
	}
	if query := mq.withMemoRelation; query != nil {
		if err := mq.loadMemoRelation(ctx, query, nodes,
			func(n *Memo) { n.Edges.MemoRelation = []*MemoRelation{} },
			func(n *Memo, e *MemoRelation) { n.Edges.MemoRelation = append(n.Edges.MemoRelation, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (mq *MemoQuery) loadRelatedMemo(ctx context.Context, query *MemoQuery, nodes []*Memo, init func(*Memo), assign func(*Memo, *Memo)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Memo)
	nids := make(map[int]map[*Memo]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(memo.RelatedMemoTable)
		s.Join(joinT).On(s.C(memo.FieldID), joinT.C(memo.RelatedMemoPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(memo.RelatedMemoPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(memo.RelatedMemoPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Memo]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Memo](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "related_memo" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (mq *MemoQuery) loadMemoRelation(ctx context.Context, query *MemoRelationQuery, nodes []*Memo, init func(*Memo), assign func(*Memo, *MemoRelation)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Memo)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(memorelation.FieldMemoID)
	}
	query.Where(predicate.MemoRelation(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(memo.MemoRelationColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.MemoID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "memo_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (mq *MemoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mq.querySpec()
	_spec.Node.Columns = mq.ctx.Fields
	if len(mq.ctx.Fields) > 0 {
		_spec.Unique = mq.ctx.Unique != nil && *mq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mq.driver, _spec)
}

func (mq *MemoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(memo.Table, memo.Columns, sqlgraph.NewFieldSpec(memo.FieldID, field.TypeInt))
	_spec.From = mq.sql
	if unique := mq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mq.path != nil {
		_spec.Unique = true
	}
	if fields := mq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, memo.FieldID)
		for i := range fields {
			if fields[i] != memo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mq *MemoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mq.driver.Dialect())
	t1 := builder.Table(memo.Table)
	columns := mq.ctx.Fields
	if len(columns) == 0 {
		columns = memo.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mq.sql != nil {
		selector = mq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mq.ctx.Unique != nil && *mq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mq.predicates {
		p(selector)
	}
	for _, p := range mq.order {
		p(selector)
	}
	if offset := mq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MemoGroupBy is the group-by builder for Memo entities.
type MemoGroupBy struct {
	selector
	build *MemoQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mgb *MemoGroupBy) Aggregate(fns ...AggregateFunc) *MemoGroupBy {
	mgb.fns = append(mgb.fns, fns...)
	return mgb
}

// Scan applies the selector query and scans the result into the given value.
func (mgb *MemoGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mgb.build.ctx, "GroupBy")
	if err := mgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MemoQuery, *MemoGroupBy](ctx, mgb.build, mgb, mgb.build.inters, v)
}

func (mgb *MemoGroupBy) sqlScan(ctx context.Context, root *MemoQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mgb.fns))
	for _, fn := range mgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mgb.flds)+len(mgb.fns))
		for _, f := range *mgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MemoSelect is the builder for selecting fields of Memo entities.
type MemoSelect struct {
	*MemoQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ms *MemoSelect) Aggregate(fns ...AggregateFunc) *MemoSelect {
	ms.fns = append(ms.fns, fns...)
	return ms
}

// Scan applies the selector query and scans the result into the given value.
func (ms *MemoSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ms.ctx, "Select")
	if err := ms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MemoQuery, *MemoSelect](ctx, ms.MemoQuery, ms, ms.inters, v)
}

func (ms *MemoSelect) sqlScan(ctx context.Context, root *MemoQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ms.fns))
	for _, fn := range ms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
