// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/usememos/memos/ent/memo"
	"github.com/usememos/memos/ent/memorelation"
	"github.com/usememos/memos/ent/predicate"
)

// MemoRelationQuery is the builder for querying MemoRelation entities.
type MemoRelationQuery struct {
	config
	ctx             *QueryContext
	order           []memorelation.OrderOption
	inters          []Interceptor
	predicates      []predicate.MemoRelation
	withMemo        *MemoQuery
	withRelatedMemo *MemoQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MemoRelationQuery builder.
func (mrq *MemoRelationQuery) Where(ps ...predicate.MemoRelation) *MemoRelationQuery {
	mrq.predicates = append(mrq.predicates, ps...)
	return mrq
}

// Limit the number of records to be returned by this query.
func (mrq *MemoRelationQuery) Limit(limit int) *MemoRelationQuery {
	mrq.ctx.Limit = &limit
	return mrq
}

// Offset to start from.
func (mrq *MemoRelationQuery) Offset(offset int) *MemoRelationQuery {
	mrq.ctx.Offset = &offset
	return mrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mrq *MemoRelationQuery) Unique(unique bool) *MemoRelationQuery {
	mrq.ctx.Unique = &unique
	return mrq
}

// Order specifies how the records should be ordered.
func (mrq *MemoRelationQuery) Order(o ...memorelation.OrderOption) *MemoRelationQuery {
	mrq.order = append(mrq.order, o...)
	return mrq
}

// QueryMemo chains the current query on the "memo" edge.
func (mrq *MemoRelationQuery) QueryMemo() *MemoQuery {
	query := (&MemoClient{config: mrq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(memorelation.Table, memorelation.FieldID, selector),
			sqlgraph.To(memo.Table, memo.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, memorelation.MemoTable, memorelation.MemoColumn),
		)
		fromU = sqlgraph.SetNeighbors(mrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRelatedMemo chains the current query on the "related_memo" edge.
func (mrq *MemoRelationQuery) QueryRelatedMemo() *MemoQuery {
	query := (&MemoClient{config: mrq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(memorelation.Table, memorelation.FieldID, selector),
			sqlgraph.To(memo.Table, memo.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, memorelation.RelatedMemoTable, memorelation.RelatedMemoColumn),
		)
		fromU = sqlgraph.SetNeighbors(mrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MemoRelation entity from the query.
// Returns a *NotFoundError when no MemoRelation was found.
func (mrq *MemoRelationQuery) First(ctx context.Context) (*MemoRelation, error) {
	nodes, err := mrq.Limit(1).All(setContextOp(ctx, mrq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{memorelation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mrq *MemoRelationQuery) FirstX(ctx context.Context) *MemoRelation {
	node, err := mrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MemoRelation ID from the query.
// Returns a *NotFoundError when no MemoRelation ID was found.
func (mrq *MemoRelationQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mrq.Limit(1).IDs(setContextOp(ctx, mrq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{memorelation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mrq *MemoRelationQuery) FirstIDX(ctx context.Context) int {
	id, err := mrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MemoRelation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MemoRelation entity is found.
// Returns a *NotFoundError when no MemoRelation entities are found.
func (mrq *MemoRelationQuery) Only(ctx context.Context) (*MemoRelation, error) {
	nodes, err := mrq.Limit(2).All(setContextOp(ctx, mrq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{memorelation.Label}
	default:
		return nil, &NotSingularError{memorelation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mrq *MemoRelationQuery) OnlyX(ctx context.Context) *MemoRelation {
	node, err := mrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MemoRelation ID in the query.
// Returns a *NotSingularError when more than one MemoRelation ID is found.
// Returns a *NotFoundError when no entities are found.
func (mrq *MemoRelationQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mrq.Limit(2).IDs(setContextOp(ctx, mrq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{memorelation.Label}
	default:
		err = &NotSingularError{memorelation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mrq *MemoRelationQuery) OnlyIDX(ctx context.Context) int {
	id, err := mrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MemoRelations.
func (mrq *MemoRelationQuery) All(ctx context.Context) ([]*MemoRelation, error) {
	ctx = setContextOp(ctx, mrq.ctx, "All")
	if err := mrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MemoRelation, *MemoRelationQuery]()
	return withInterceptors[[]*MemoRelation](ctx, mrq, qr, mrq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mrq *MemoRelationQuery) AllX(ctx context.Context) []*MemoRelation {
	nodes, err := mrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MemoRelation IDs.
func (mrq *MemoRelationQuery) IDs(ctx context.Context) (ids []int, err error) {
	if mrq.ctx.Unique == nil && mrq.path != nil {
		mrq.Unique(true)
	}
	ctx = setContextOp(ctx, mrq.ctx, "IDs")
	if err = mrq.Select(memorelation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mrq *MemoRelationQuery) IDsX(ctx context.Context) []int {
	ids, err := mrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mrq *MemoRelationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mrq.ctx, "Count")
	if err := mrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mrq, querierCount[*MemoRelationQuery](), mrq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mrq *MemoRelationQuery) CountX(ctx context.Context) int {
	count, err := mrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mrq *MemoRelationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mrq.ctx, "Exist")
	switch _, err := mrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mrq *MemoRelationQuery) ExistX(ctx context.Context) bool {
	exist, err := mrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MemoRelationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mrq *MemoRelationQuery) Clone() *MemoRelationQuery {
	if mrq == nil {
		return nil
	}
	return &MemoRelationQuery{
		config:          mrq.config,
		ctx:             mrq.ctx.Clone(),
		order:           append([]memorelation.OrderOption{}, mrq.order...),
		inters:          append([]Interceptor{}, mrq.inters...),
		predicates:      append([]predicate.MemoRelation{}, mrq.predicates...),
		withMemo:        mrq.withMemo.Clone(),
		withRelatedMemo: mrq.withRelatedMemo.Clone(),
		// clone intermediate query.
		sql:  mrq.sql.Clone(),
		path: mrq.path,
	}
}

// WithMemo tells the query-builder to eager-load the nodes that are connected to
// the "memo" edge. The optional arguments are used to configure the query builder of the edge.
func (mrq *MemoRelationQuery) WithMemo(opts ...func(*MemoQuery)) *MemoRelationQuery {
	query := (&MemoClient{config: mrq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mrq.withMemo = query
	return mrq
}

// WithRelatedMemo tells the query-builder to eager-load the nodes that are connected to
// the "related_memo" edge. The optional arguments are used to configure the query builder of the edge.
func (mrq *MemoRelationQuery) WithRelatedMemo(opts ...func(*MemoQuery)) *MemoRelationQuery {
	query := (&MemoClient{config: mrq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mrq.withRelatedMemo = query
	return mrq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Type string `json:"type,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MemoRelation.Query().
//		GroupBy(memorelation.FieldType).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mrq *MemoRelationQuery) GroupBy(field string, fields ...string) *MemoRelationGroupBy {
	mrq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MemoRelationGroupBy{build: mrq}
	grbuild.flds = &mrq.ctx.Fields
	grbuild.label = memorelation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Type string `json:"type,omitempty"`
//	}
//
//	client.MemoRelation.Query().
//		Select(memorelation.FieldType).
//		Scan(ctx, &v)
func (mrq *MemoRelationQuery) Select(fields ...string) *MemoRelationSelect {
	mrq.ctx.Fields = append(mrq.ctx.Fields, fields...)
	sbuild := &MemoRelationSelect{MemoRelationQuery: mrq}
	sbuild.label = memorelation.Label
	sbuild.flds, sbuild.scan = &mrq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MemoRelationSelect configured with the given aggregations.
func (mrq *MemoRelationQuery) Aggregate(fns ...AggregateFunc) *MemoRelationSelect {
	return mrq.Select().Aggregate(fns...)
}

func (mrq *MemoRelationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mrq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mrq); err != nil {
				return err
			}
		}
	}
	for _, f := range mrq.ctx.Fields {
		if !memorelation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mrq.path != nil {
		prev, err := mrq.path(ctx)
		if err != nil {
			return err
		}
		mrq.sql = prev
	}
	return nil
}

func (mrq *MemoRelationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MemoRelation, error) {
	var (
		nodes       = []*MemoRelation{}
		_spec       = mrq.querySpec()
		loadedTypes = [2]bool{
			mrq.withMemo != nil,
			mrq.withRelatedMemo != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MemoRelation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MemoRelation{config: mrq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := mrq.withMemo; query != nil {
		if err := mrq.loadMemo(ctx, query, nodes, nil,
			func(n *MemoRelation, e *Memo) { n.Edges.Memo = e }); err != nil {
			return nil, err
		}
	}
	if query := mrq.withRelatedMemo; query != nil {
		if err := mrq.loadRelatedMemo(ctx, query, nodes, nil,
			func(n *MemoRelation, e *Memo) { n.Edges.RelatedMemo = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (mrq *MemoRelationQuery) loadMemo(ctx context.Context, query *MemoQuery, nodes []*MemoRelation, init func(*MemoRelation), assign func(*MemoRelation, *Memo)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*MemoRelation)
	for i := range nodes {
		fk := nodes[i].MemoID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(memo.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "memo_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (mrq *MemoRelationQuery) loadRelatedMemo(ctx context.Context, query *MemoQuery, nodes []*MemoRelation, init func(*MemoRelation), assign func(*MemoRelation, *Memo)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*MemoRelation)
	for i := range nodes {
		fk := nodes[i].RelatedMemoID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(memo.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "related_memo_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (mrq *MemoRelationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mrq.querySpec()
	_spec.Node.Columns = mrq.ctx.Fields
	if len(mrq.ctx.Fields) > 0 {
		_spec.Unique = mrq.ctx.Unique != nil && *mrq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mrq.driver, _spec)
}

func (mrq *MemoRelationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(memorelation.Table, memorelation.Columns, sqlgraph.NewFieldSpec(memorelation.FieldID, field.TypeInt))
	_spec.From = mrq.sql
	if unique := mrq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mrq.path != nil {
		_spec.Unique = true
	}
	if fields := mrq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, memorelation.FieldID)
		for i := range fields {
			if fields[i] != memorelation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if mrq.withMemo != nil {
			_spec.Node.AddColumnOnce(memorelation.FieldMemoID)
		}
		if mrq.withRelatedMemo != nil {
			_spec.Node.AddColumnOnce(memorelation.FieldRelatedMemoID)
		}
	}
	if ps := mrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mrq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mrq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mrq *MemoRelationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mrq.driver.Dialect())
	t1 := builder.Table(memorelation.Table)
	columns := mrq.ctx.Fields
	if len(columns) == 0 {
		columns = memorelation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mrq.sql != nil {
		selector = mrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mrq.ctx.Unique != nil && *mrq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mrq.predicates {
		p(selector)
	}
	for _, p := range mrq.order {
		p(selector)
	}
	if offset := mrq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mrq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MemoRelationGroupBy is the group-by builder for MemoRelation entities.
type MemoRelationGroupBy struct {
	selector
	build *MemoRelationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mrgb *MemoRelationGroupBy) Aggregate(fns ...AggregateFunc) *MemoRelationGroupBy {
	mrgb.fns = append(mrgb.fns, fns...)
	return mrgb
}

// Scan applies the selector query and scans the result into the given value.
func (mrgb *MemoRelationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mrgb.build.ctx, "GroupBy")
	if err := mrgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MemoRelationQuery, *MemoRelationGroupBy](ctx, mrgb.build, mrgb, mrgb.build.inters, v)
}

func (mrgb *MemoRelationGroupBy) sqlScan(ctx context.Context, root *MemoRelationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mrgb.fns))
	for _, fn := range mrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mrgb.flds)+len(mrgb.fns))
		for _, f := range *mrgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mrgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mrgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MemoRelationSelect is the builder for selecting fields of MemoRelation entities.
type MemoRelationSelect struct {
	*MemoRelationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mrs *MemoRelationSelect) Aggregate(fns ...AggregateFunc) *MemoRelationSelect {
	mrs.fns = append(mrs.fns, fns...)
	return mrs
}

// Scan applies the selector query and scans the result into the given value.
func (mrs *MemoRelationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mrs.ctx, "Select")
	if err := mrs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MemoRelationQuery, *MemoRelationSelect](ctx, mrs.MemoRelationQuery, mrs, mrs.inters, v)
}

func (mrs *MemoRelationSelect) sqlScan(ctx context.Context, root *MemoRelationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mrs.fns))
	for _, fn := range mrs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mrs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
