// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file api/v1/link_service.proto (package memos.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_google_api_client } from "../../google/api/client_pb";
import { file_google_api_field_behavior } from "../../google/api/field_behavior_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/link_service.proto.
 */
export const file_api_v1_link_service: GenFile = /*@__PURE__*/
  fileDesc("ChlhcGkvdjEvbGlua19zZXJ2aWNlLnByb3RvEgxtZW1vcy5hcGkudjEiKgoWR2V0TGlua01ldGFkYXRhUmVxdWVzdBIQCgN1cmwYASABKAlCA+BBAiJBCgxMaW5rTWV0YWRhdGESDQoFdGl0bGUYASABKAkSEwoLZGVzY3JpcHRpb24YAiABKAkSDQoFaW1hZ2UYAyABKAkyiAEKC0xpbmtTZXJ2aWNlEnkKD0dldExpbmtNZXRhZGF0YRIkLm1lbW9zLmFwaS52MS5HZXRMaW5rTWV0YWRhdGFSZXF1ZXN0GhoubWVtb3MuYXBpLnYxLkxpbmtNZXRhZGF0YSIk2kEDdXJsgtPkkwIYEhYvYXBpL3YxL2xpbmtzL21ldGFkYXRhQqgBChBjb20ubWVtb3MuYXBpLnYxQhBMaW5rU2VydmljZVByb3RvUAFaMGdpdGh1Yi5jb20vdXNlbWVtb3MvbWVtb3MvcHJvdG8vZ2VuL2FwaS92MTthcGl2MaICA01BWKoCDE1lbW9zLkFwaS5WMcoCDE1lbW9zXEFwaVxWMeICGE1lbW9zXEFwaVxWMVxHUEJNZXRhZGF0YeoCDk1lbW9zOjpBcGk6OlYxYgZwcm90bzM", [file_google_api_annotations, file_google_api_client, file_google_api_field_behavior]);

/**
 * Request message for GetLinkMetadata method.
 *
 * @generated from message memos.api.v1.GetLinkMetadataRequest
 */
export type GetLinkMetadataRequest = Message<"memos.api.v1.GetLinkMetadataRequest"> & {
  /**
   * The URL to fetch metadata for.
   *
   * @generated from field: string url = 1;
   */
  url: string;
};

/**
 * Describes the message memos.api.v1.GetLinkMetadataRequest.
 * Use `create(GetLinkMetadataRequestSchema)` to create a new message.
 */
export const GetLinkMetadataRequestSchema: GenMessage<GetLinkMetadataRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_link_service, 0);

/**
 * LinkMetadata contains OpenGraph metadata for a link.
 *
 * @generated from message memos.api.v1.LinkMetadata
 */
export type LinkMetadata = Message<"memos.api.v1.LinkMetadata"> & {
  /**
   * The title of the link (from og:title or <title> tag).
   *
   * @generated from field: string title = 1;
   */
  title: string;

  /**
   * The description of the link (from og:description or <meta name="description">).
   *
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * The preview image URL (from og:image).
   *
   * @generated from field: string image = 3;
   */
  image: string;
};

/**
 * Describes the message memos.api.v1.LinkMetadata.
 * Use `create(LinkMetadataSchema)` to create a new message.
 */
export const LinkMetadataSchema: GenMessage<LinkMetadata> = /*@__PURE__*/
  messageDesc(file_api_v1_link_service, 1);

/**
 * @generated from service memos.api.v1.LinkService
 */
export const LinkService: GenService<{
  /**
   * GetLinkMetadata fetches OpenGraph metadata for a given URL.
   *
   * @generated from rpc memos.api.v1.LinkService.GetLinkMetadata
   */
  getLinkMetadata: {
    methodKind: "unary";
    input: typeof GetLinkMetadataRequestSchema;
    output: typeof LinkMetadataSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_link_service, 0);

